version: '3'

services:

  mtproxy:
    image: alexdoesh/mtproxy
    container_name: mtproxy
    # command: --add --your --commands
    # environment:
    #   - OVERRIDE=SOME
    #   - VARIABLES=HERE
    volumes:
      - ./tg:/data
    ports:
      - "2398:2398"
      - "443:443"
    networks:
      - tg_stack

networks:
  tg_stack:

